server:
  port: 8085
  servlet:
    context-path: /clinic-management-service
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://${DATABASE_ENDPOINT}:${DATABASE_ENDPOINT_PORT:5432}/cmdb
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-master.yaml"
logging:
  excluded-requests: /actuator/health, /swagger-ui, /api-docs
springdoc:
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
  api-docs.path: /api-docs
jwt:
  secret: ${JWT_SECRET}

# -----------------------------------------------------------------#
# Actuator configuration
management:
  endpoint:
    enabled-by-default: false
    health:
      show-details: always
      enabled: true
      info.enabled: true
  health:
    defaults.enabled: true
    db.enabled: true